### ISSUE TITLE
Files for gromacs

### ISSUE THREAD

**Issue by aminsagar** [ajaymur91/pucker-correction#1]
Hello.
Thanks for making these parameters available.
I would like to use these with a99sb-disp force field which is available only in gromacs format. So, I can't generate the system with tleap and then convert to gromacs with Parmed. Is it possible for you to share these parameters in gromacs format so that I can use them with pdb2gmx.
Thanks again.
Amin
Center de Biologie Structurale,
Montpellier,
France.

**Comment by ajaymur91** [comment]
@aminsagar The pucker correction parameters were originally designed to fix the Amber FF14SB forcefield. That said, it might work reasonably well for forcefields similar to Amber FF14SB. 

I don't exactly understand which parameters you need but one thing you could try is the following:
1) using the script i provide, create a (FF14SB based) forcefield for your protein using this github repo and convert to gromacs format. Then from the generated gromacs files copy the parameters you need.
2) If you are unable to do 1, could you upload the structure of your protein and provide a detailed description of your requirement and I cant take a look at it.

**Comment by aminsagar** [comment]
Thanks. I think I basically followed the procedure that you suggested.
I added the following lines to the aminoacids.rtp file
```
[ PRF ]
 [ atoms ]
   N    N            -0.146327     1
   CD   CT           -0.189338     2
   HD1  H1            0.094775     3
   HD2  H1            0.094775     4
   CG   CT            0.420275     5
   HF   Hf            0.017040     6
   F1   f            -0.297174     7
   CB   CT           -0.226092     8
   HB1  HC            0.091203     9
   HB2  HC            0.091203    10
   CA   CT           -0.087012    11
   HA   H1            0.102478    12
   C    C             0.540229    13
   O    O            -0.506134    14
 [ bonds ]
     N    CD
     N    CA
    CD   HD1
    CD   HD2
    CD    CG
    CG   HF
    CG   F1
    CG    CB
    CB   HB1
    CB   HB2
    CB    CA
    CA    HA
    CA     C
     C     O
    -C     N

   [ impropers ]
    CA    +N     C     O
    -C    CD     N    CA
```
In ffbonded.itp, I added
```
[ angletypes ]
;  i    j    k  func       th0       cth
CT  CT  Hf           1   109.500    418.400 ; PRF
CT  CT  f            1   109.240    553.116 ; PRF
Hf  CT  f            1   107.900    430.123 ; PRF

[ dihedraltypes ]
;i   j   k   l     func
 N   CT  CT  f     9       0.0      0.65084     3  ; PRF
 f   CT  CT  CT    9       0.0      0.65084     3  ; PRF
 N   CT  CT  Hf    9       0.0      0.65084     3  ; PRF
 H1  CT  CT  Hf    9       0.0      0.65084     3  ; PRF
 H1  CT  CT  f     9       0.0      0.79496     1  ; PRF
 f   CT  CT  HC    9       0.0      0.79496     1  ; PRF
 Hf  CT  CT  HC    9       0.0      0.62760     3  ; PRF
 Hf  CT  CT  CT    9       0.0      0.66944     3  ; PRF
```
In atomtype.atp, I added
```
Hf                 1.0080       ; Hydrogen for F
f                 19.00000      ; F for Fluoroproline
```
In ffnonbonded.itp, I added
```
[ atomtypes ]
; name      at.num  mass     charge ptype  sigma      epsilon
Hf           1       1.008   0.0000  A   0.2          0.1745999 ; PRF
f            9      19.0     0.0000  A   0.28         0.0908199 ; PRF
```
Finally, I added the new residue in residuetypes.dat
```
PRF     Protein
```
Does this reasonable to you. Anything else that I should modify?

Thanks again.

**Comment by ajaymur91** [comment]
This looks reasonable. Also, if you need to model Proline ring puckering accurately, remember to use the plumed.dat file generated by my script
